# Generated by Django 2.1.5 on 2019-02-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='date_ordered',
            new_name='date_sent',
        ),
        migrations.AlterField(
            model_name='requisition',
            name='order_ref',
            field=models.CharField(blank=True, help_text='Enter EROS reference number for requisition', max_length=20, null=True, verbose_name='Requisition Reference EROS'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_status',
            field=models.CharField(choices=[('incomplete', 'INCOMPLETE'), ('awaiting_auth', 'AWAITING AUTHORIZATION'), ('authorized', 'AUTHORIZED'), ('pending', 'REQUISITION SENT'), ('complete', 'REQUISITION COMPLETE')], default='incomplete', max_length=24),
        ),
    ]
