# Generated by Django 2.1.5 on 2019-02-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190201_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='requisition_status',
            field=models.CharField(choices=[('incomplete', 'INCOMPLETE'), ('awaiting_auth', 'AWAITING AUTHORIZATION'), ('authorized', 'AUTHORIZED'), ('sent', 'SENT'), ('complete', 'COMPLETE')], default='incomplete', max_length=24),
        ),
    ]
