# Generated by Django 2.1.5 on 2019-02-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20190201_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Team'),
        ),
    ]
