# Generated by Django 2.1.5 on 2019-02-14 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_order_orderer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'ordering': ['-stock'], 'permissions': (('can_update_stock', 'Update Product Instance Stock'),)},
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='requisition_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Requisition'),
        ),
    ]
