# Generated by Django 2.1.5 on 2019-02-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20190214_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'ordering': ['-stock']},
        ),
    ]
