# Generated by Django 2.1.5 on 2019-02-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20190215_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': (('able_to_create_new_supplier', 'Create New Supplier'), ('able_to_update_supplier', 'Update Supplier'), ('able_to_delete_supplier', 'Delete Supplier'))},
        ),
    ]
