# Generated by Django 2.1.5 on 2019-02-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20190225_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': (('can_create_new_supplier', 'Able to Create New Supplier'), ('can_update_supplier', 'Able to Update Supplier'), ('can_delete_supplier', 'Able to Delete Supplier'))},
        ),
    ]
