# Generated by Django 2.1.5 on 2019-02-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20190225_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'permissions': (('can_create_new_requisition', 'Able to Create New Requisition'), ('can_update_requisition', 'Able to Update Requisition'), ('can_delete_requisition', 'Able to Delete Requisition'))},
        ),
    ]
