# Generated by Django 2.1.5 on 2019-02-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20190225_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('can_create_new_order', 'Able to Create New Order'), ('can_update_order', 'Able to Update Order'), ('can_delete_order', 'Able to Delete Order'))},
        ),
    ]
