# Generated by Django 2.1.5 on 2019-02-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20190225_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('can_create_new_team', 'Able to Create New Team'), ('can_update_team', 'Able to Update Team'), ('can_delete_team', 'Able to Delete Team'))},
        ),
    ]
