# Generated by Django 2.1.5 on 2019-02-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_auto_20190225_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'permissions': (('can_create_new_storage', 'Able to Create New Storage'), ('can_update_storage', 'Able to Update Storage'), ('can_delete_storage', 'Able to Delete Storage'))},
        ),
    ]
