# Generated by Django 2.1.5 on 2019-02-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20190225_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'ordering': ['-stock'], 'permissions': (('can_create_new_product_instance', 'Able to Create New Product Instance'), ('can_update_product_instance', 'Able to Update Product Instance'), ('can_delete_product_instance', 'Able to Delete Product Instance'))},
        ),
    ]
