# Generated by Django 2.1.5 on 2019-02-28 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20190228_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='authoriser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
