# Generated by Django 2.1.5 on 2019-02-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20190228_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='supplier',
        ),
    ]
