# Generated by Django 2.1.5 on 2019-02-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_remove_requisition_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order_created', 'ORDER CREATED'), ('received', 'RECEIVED'), ('received_frozen', 'RECEIVED FROZEN'), ('delayed', 'ORDER DELAYED')], default='order_created', max_length=24),
        ),
    ]
