# Generated by Django 2.1.5 on 2019-02-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, help_text='Enter a comment if required', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Created', 'ORDER CREATED'), ('Received', 'RECEIVED'), ('Received Frozen', 'RECEIVED FROZEN'), ('Delayed', 'ORDER DELAYED')], default='order_created', max_length=24),
        ),
    ]
