# Generated by Django 2.1.5 on 2019-02-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20190228_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, help_text='Enter comment if required', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='comments',
            field=models.TextField(blank=True, help_text='Enter comment if required', max_length=1000, null=True),
        ),
    ]
