# Generated by Django 2.1.5 on 2019-02-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20190228_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='requisition_status',
            field=models.CharField(choices=[('Incomplete', 'INCOMPLETE'), ('Awaiting Authorization', 'AWAITING AUTHORIZATION'), ('Authorized', 'AUTHORIZED'), ('Sent', 'SENT'), ('Complete', 'COMPLETE')], default='incomplete', max_length=24),
        ),
    ]
