# Generated by Django 2.1.5 on 2019-02-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_auto_20190228_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='requisition_status',
            field=models.CharField(choices=[('Incomplete', 'INCOMPLETE'), ('Awaiting Authorisation', 'AWAITING AUTHORISATION'), ('Authorised', 'AUTHORISED'), ('Sent', 'SENT'), ('Complete', 'COMPLETE')], default='incomplete', max_length=24),
        ),
    ]
