# Generated by Django 2.1.5 on 2019-03-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_auto_20190228_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='urgency',
            field=models.CharField(choices=[('Urgent', 'URGENT'), ('Non-Urgent', 'NON-URGENT')], default='Non-Urgent', max_length=10),
        ),
    ]
