# Generated by Django 2.1.5 on 2019-03-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_auto_20190311_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-requisition_id'], 'permissions': (('can_create_new_order', 'Able to Create New Order'), ('can_update_order', 'Able to Update Order'), ('can_delete_order', 'Able to Delete Order'))},
        ),
    ]
