# Generated by Django 2.1.5 on 2019-03-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_auto_20190311_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'ordering': ['stock'], 'permissions': (('can_create_new_product_instance', 'Able to Create New Product Instance'), ('can_update_product_instance', 'Able to Update Product Instance'), ('can_delete_product_instance', 'Able to Delete Product Instance'))},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'permissions': (('can_create_new_product_type', 'Able to Create New Product Type'), ('can_update_product_type', 'Able to Update Product Type'), ('can_delete_product_type', 'Able to Delete Product Type'))},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['name'], 'permissions': (('can_create_new_storage', 'Able to Create New Storage'), ('can_update_storage', 'Able to Update Storage'), ('can_delete_storage', 'Able to Delete Storage'))},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'permissions': (('can_create_new_team', 'Able to Create New Team'), ('can_update_team', 'Able to Update Team'), ('can_delete_team', 'Able to Delete Team'))},
        ),
    ]
