# Generated by Django 2.1.5 on 2019-03-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_auto_20190311_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='requisition_status',
            field=models.CharField(choices=[('Incomplete', 'INCOMPLETE'), ('Authorised', 'AUTHORISED'), ('Sent', 'SENT'), ('Complete', 'COMPLETE')], default='incomplete', max_length=24),
        ),
    ]
