# Generated by Django 2.1.5 on 2019-03-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_auto_20190312_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='agent',
            field=models.CharField(blank=True, help_text='Enter agent name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter supplier contact email', max_length=200, null=True),
        ),
    ]
