# Generated by Django 2.1.5 on 2019-03-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_auto_20190312_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['supplier', 'name'], 'permissions': (('can_create_new_product_type', 'Able to Create New Product Type'), ('can_update_product_type', 'Able to Update Product Type'), ('can_delete_product_type', 'Able to Delete Product Type'))},
        ),
    ]
