# Generated by Django 2.1.5 on 2019-03-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_auto_20190314_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delivered',
            field=models.DateField(blank=True, help_text='Enter date requisition was received (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Enter expiry date of Lot (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lot_id',
            field=models.CharField(blank=True, help_text='Enter Lot Number of product upon delivery', max_length=20, null=True, verbose_name='LOT Bumber'),
        ),
        migrations.AddField(
            model_name='order',
            name='qc_status',
            field=models.CharField(choices=[('N/a', 'N/A'), ('Room Temp', 'ROOM TEMP'), ('Dry Ice', 'DRY ICE'), ('Cold Block', 'COLD BLOCK')], default='N/a', max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Team'),
        ),
        migrations.AddField(
            model_name='order',
            name='urgency',
            field=models.CharField(choices=[('Urgent', 'URGENT'), ('Non-Urgent', 'NON-URGENT')], default='Non-Urgent', max_length=10),
        ),
        migrations.AddField(
            model_name='producttype',
            name='lead_time',
            field=models.IntegerField(blank=True, help_text='Estimated delivery time required', null=True, verbose_name='Lead time (Days)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Created', 'CREATED'), ('Order Sent', 'SENT'), ('Part Received', 'PART RECEIVED'), ('Complete', 'COMPLETE')], default='order_created', max_length=24),
        ),
    ]
