# Generated by Django 2.1.5 on 2019-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_auto_20190314_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivered',
            field=models.DateField(blank=True, help_text='Enter date requisition was received (YYYY-MM-DD)', null=True, verbose_name='Date Completed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lot_id',
            field=models.CharField(blank=True, help_text='Enter Lot Number of product upon delivery', max_length=20, null=True, verbose_name='LOT Number'),
        ),
    ]
