# Generated by Django 2.1.5 on 2019-03-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0051_auto_20190318_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter supplier contact email', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(help_text='Enter supplier contact telephone number', max_length=50),
        ),
    ]
