# Generated by Django 2.1.5 on 2019-03-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_auto_20190321_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='maximum',
            field=models.DecimalField(decimal_places=2, help_text='Enter maximum temperature (°C)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='minimum',
            field=models.DecimalField(decimal_places=2, help_text='Enter minimum temperature (°C)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='name',
            field=models.CharField(blank=True, help_text='Enter name for temperature range', max_length=200),
        ),
    ]
