# Generated by Django 2.1.5 on 2019-03-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_auto_20190321_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='temp_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Temperature'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='agent',
            field=models.CharField(blank=True, help_text='Enter agent name', max_length=200),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='name',
            field=models.CharField(help_text='Enter name for temperature range', max_length=200),
        ),
    ]
