# Generated by Django 2.1.5 on 2019-03-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_auto_20190321_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='agent',
            field=models.CharField(blank=True, help_text='Enter agent name', max_length=200, null=True),
        ),
    ]
