# Generated by Django 2.1.5 on 2019-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_auto_20190321_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='agent',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, help_text='Enter an address for the supplier', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
