# Generated by Django 2.1.5 on 2019-03-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_auto_20190321_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, help_text='Enter an address for the supplier', max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='comments',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
