# Generated by Django 2.1.5 on 2019-03-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0058_auto_20190321_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['name'], 'permissions': (('can_create_new_temperature', 'Able to Create New Temperature'), ('can_update_temperature', 'Able to Update Temoperature'), ('can_delete_temperature', 'Able to Delete Temperature'))},
        ),
    ]
