# Generated by Django 2.1.5 on 2019-03-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0059_auto_20190321_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='lead_time',
            field=models.IntegerField(blank=True, help_text='Estimated delivery time required', max_length=3, null=True, verbose_name='Lead time (Days)'),
        ),
    ]
