# Generated by Django 2.1.5 on 2019-03-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0062_auto_20190322_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'permissions': (('can_create_new_product_type', 'Able to Create New Product Type'), ('can_update_product_type', 'Able to Update Product Type'), ('can_delete_product_type', 'Able to Delete Product Type'))},
        ),
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Enter expiry date of Lot (YYYY-MM-DD)', null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.ProductType', verbose_name='Product Type'),
        ),
    ]
